PREFIX jams: <http://w3id.org/polifonia/ontology/jams/>
PREFIX mp:  <http://w3id.org/polifonia/ontology/musical-performance/>
PREFIX mc:  <http://w3id.org/polifonia/ontology/musical-composition/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?composerName
WHERE {
  ?composition a mc:MusicalComposition ;
    mc:title "Savoy Blues" ;
    mc:hasComposer ?composer .
  ?composer rdfs:label ?composerName .
} 
